_modelid = "SWBForms";
//_dataStore = "embedmongodb";
_dataStore = "mongodb";
//_dataStore = "ts_leveldb";
roles={prog:"Programador", su:"Super User",admin:"Administrator",user:"User"};
eng.config.appName="SWBForms";
eng.config.appURL="https://github.com/SWBForms2";
eng.config.appSkin="skin-blue";
eng.config.compileDS=false;                                         //compile admin_db.js
